### PR TITLE
Update to 2.11.1

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
I haven't run the updated plugin yet.

**Comment by hfiguiere** [comment]
Also I'm not sure why the f-e-d-c bot didn't run.

**Comment by Bleuzen** [comment]
> I haven't run the updated plugin yet.

VST3 works here in both Carla and Ardour

LV2 crashes both hosts

> Also I'm not sure why the f-e-d-c bot didn't run.

The current pattern is:

`^v([\\d.]+)$`

This does not match the tag names

grafik

because `\\` in regex usually means one literal backslash (which is not contained in the tag names).
Removing one backslash works:

grafik

However other flatpaks also use this pattern here on flathub and it works over there, for example see Carla:
https://github.com/flathub/studio.kx.carla/blob/123be1a3aec3cd49e1584a34ff2db762415b9220/studio.kx.carla.json#L285

So... seems to be working for the regex flavor of f-e-d-c.

Not sure why it doesn't work for ChowTapeModel. Probably try to remove one backslash and see what happens.

**Comment by hfiguiere** [comment]
here the `\\` is escaped by JSON. I checked the pattern, my build script now valide the f-e-d-c, and pre-update it told me there was a new one.

**Comment by Bleuzen** [comment]
> LV2 crashes both hosts

not a new problem, also happens with 2.11.0
See: https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel/issues/8

**Comment by Bleuzen** [comment]
Merged, since the new version doesn't make anything worse.
The crash can be discussed in https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel/issues/8

**Pull request merged**
